---
# file: dev.yml

# ----------------------------------------------------------------------------------------------------------------------
# "lookup": string
#
# indicates the lookup to perform. the arguments of a lookup are different from lookup to lookup
#
# Supported Lookups:
# ------------------
#
# inet('<network interface>') -> inet('eth0')
# exec('<program path>')      -> exec('/path/to/custom/lookup')
# http('method', 'url')       -> http('GET', 'https://10.0.0.1:8055')
#
# Dynamic Lookup:
# ---------------
#
# The lookup can by dynamically set when the OS boots using <%= ENV['dw_presence_lookup'] => and passing in a custom
# string to the environment variable that contains one of the above supported lookups and its associated parameters.
#
# External and HTTP response format:
# ---------------------------------
#
# When using exec or HTTP(S) lookups the program or service should return a JSON payload with the following format:
#
# {
#   "external_address": "<IPv4, IPv6, or DNS name>"
# }
#
lookup: net('eth0')

# ----------------------------------------------------------------------------------------------------------------------
# "watson_configs": list<string>
#
# indicates the watson configuration files that will be updated with the discovered IP address information.
watson_configs:
  - dev/watson-foo.yml
  - dev/watson-bar.yml